<?php $this->headTitle('Home'); ?>

<style>
    body {
        background-color: #000000;
    }
    .content {
        display: flex;
        flex-direction: column;
        gap: 16px;
        position: relative;
        z-index: 1;
    }
    .content h1 {
        color: white;
        font-size: 52px;
        font-family: 'Ubuntu', system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
    }
    .blob-outer-container {
        position: fixed;
        height: 100%;
        width: 100%;
        z-index: 0;
        inset: 0;
        margin: auto;
        filter: blur(100px);
        /*opacity: 0.5;*/
    }

    .blob-inner-container {
        border-radius: 99999px;
        position: absolute;
        inset: 0;
        margin: auto;
        width: 100vw;
        height: 100vh;
        min-width: 1000px;
        overflow: hidden;
        background-color: #fff;
        transform: scale(0.7);
    }

    .blob {
        position: absolute;
        width: 100vw;
        height: 100vh;
        inset: 0;
        margin: auto;
        background: conic-gradient(from 0deg, #08f, #f60, #bbffa1, #4c00ff, #ab2666, #09f);
        animation: spinBlob 8s linear infinite;
    }

    @keyframes spinBlob {
        0% {
            transform: rotate(0deg) scale(2);
        }

        100% {
            transform: rotate(1turn) scale(2);
        }
    }


</style>

<div class="vh-100 d-flex align-items-center justify-content-center">
    <div class="blob-outer-container">
        <div class="blob-inner-container">
            <div class="blob"></div>
        </div>
    </div>

    <div class="home-page">
        <div class="content">
            <!--        <div class="quote">CSS ONLY</div>-->
            <!--        <div class="by">- Sun Tzu, The Art of War</div>-->
            <h1 class="display-4 fw-bold text-white">
                neutrino
            </h1>
            <p class="text-center">
                <a href="<?=$this->url('register.form');?>" class="text-white">Register</a>
                <a href="<?=$this->url('login.form');?>" class="text-white ms-4">Login</a>
            </p>
        </div>
    </div>
</div>
