<?php $this->headTitle('Login'); ?>

<div class="vh-100 d-flex align-items-center justify-content-center bg-light">

    <div class="card border-0 shadow-sm rounded-2" style="width: 420px; max-width: 90vw;">
        <div class="card-body p-4 p-lg-5">

            <h3 class="mb-4 text-center">Sign in</h3>

            <form id="loginForm" method="post" action="<?=$this->url('login.submit');?>">
                <div class="form-floating mb-3">
                    <input
                            type="email"
                            class="form-control"
                            id="email"
                            name="email"
                            placeholder="name@example.com"
                            value="vasildakov@gmail.com"
                            required
                    >
                    <label for="loginEmail">Email</label>
                </div>

                <div class="form-floating mb-4">
                    <input
                            type="password"
                            class="form-control"
                            id="password"
                            name="password"
                            placeholder="Password"
                            required
                    >
                    <label for="loginPassword">Password</label>
                </div>

                <div class="d-flex justify-content-between align-items-center mb-4">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">
                            Remember me
                        </label>
                    </div>
                    <a href="#" class="link-secondary small">Forgot password?</a>
                </div>

                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">
                        Sign in
                    </button>
                    <button
                            type="button"
                            class="btn btn-danger"
                            data-bs-dismiss="modal">
                        Cancel
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>