<div class="container-fluid">

    <div class="row">
        <div class="col-12">
            <h1 class="h4">Accounts</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created At</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($this->users as $account): ?>
                    <tr>
                        <td><?= $account->getShortId() ?></td>
                        <td><?= $account->getName() ?></td>
                        <td><?= $account->getEmail() ?></td>
                        <td><?= $account->getCreatedAt()->format('Y-m-d h:i:s'); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>