<div class="container-fluid">

    <div class="row p-4 bg-white">
        <div class="col-12">
            <h1 class="h4">Users</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($this->users as $user): ?>
                    <tr>
                        <td><?= $user->getShortId() ?></td>
                        <td><?= $user->getFullName() ?></td>
                        <td><?= $user->getEmail() ?></td>
                        <td><?= implode(', ', $user->getRoles()->toArray()) ?></td>
                        <td><?= $user->getCreatedAt()->format('Y-m-d h:i:s'); ?></td>
                        <td>
                            <a
                                    class="btn btn-small btn-danger"
                                    href="<?=$this->url('platform.accounts.view', ['id' => (string)$user->getId()]);?>">
                                View
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>