<?php
/**
 * @noinspection PhpFullyQualifiedNameUsageInspection
 * @noinspection PhpUndefinedMethodInspection
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */
?>

<style>
     a {
        text-decoration: none !important;
    }
</style>

<div class="sidebar">

    <div class="sidebar-header d-flex align-items-center mb-3">
        <a href="#" class="sidebar-logo"><i data-feather="airplay" class="text-white opacity-50"></i></a>
        <a href="#" class="sidebar-logo-text"><span class="text-white">Neutrino</span></a>
    </div><!-- sidebar-header -->

    <div class="sidebar-search">
        <div class="search-body">
            <i data-feather="search"></i>
            <input type="text" class="form-control" placeholder="Search...">
        </div><!-- search-body -->
    </div><!-- sidebar-search -->

    <div class="sidebar-body">
        <ul class="nav nav-sidebar">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="airplay"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="server"></i>
                    <span class="ms-1">Servers</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="users"></i>
                    <span class="ms-1">Accounts</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="shopping-bag"></i>
                    <span class="ms-1">Stores</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="credit-card"></i>
                    <span class="ms-1">Payments</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="file"></i>
                    <span class="ms-1">Invoices</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="<?= $this->url('dashboard.databases') ?>">
                    <i data-feather="database"></i>
                    <span class="ms-1">Databases</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="clock"></i>
                    <span class="ms-1">Queues</span>
                </a>
            </li>
        </ul>

        <hr>

        <nav class="nav-sidebar">
            <a href="#" class="nav-link"><i data-feather="activity"></i><span>Activity Logs</span></a>
            <a href="#" class="nav-link"><i data-feather="settings"></i><span>Settings</span></a>
            <a href="#" class="nav-link"><i data-feather="help-circle"></i><span>Help &amp; Support</span></a>
            <a href="#" class="nav-link"><i data-feather="edit-3"></i><span>Give Feedback</span></a>
            <a href="#" class="nav-link"><i data-feather="figma"></i><span>Dashboard design</span></a>
        </nav>

    </div>


    <div class="sidebar-footer">
        <a href="" class="avatar online"><span class="avatar-initial">v</span></a>
        <div class="avatar-body">
            <div class="d-flex align-items-center justify-content-between">
                <h6 class="m-0 text-white opacity-50">Vasil Dakov</h6>
                <a href="" class="footer-menu"><i class="ri-settings-4-line"></i></a>
            </div>
            <span>Superuser/Administrator</span>
        </div><!-- avatar-body -->
    </div><!-- sidebar-footer -->

    <!--div class="sidebar-footer">
        <a href="" class="footer-menu"><i class="ri-shut-down-line"></i></a>
    </div-->



</div>
