<?php
/**
 * @noinspection ALL
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="Neutrino Responsive Theme">
    <meta name="author" content="Vasil Dakov">


    <!-- Favicon -->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png"> -->

    <title>Neutrino Platform</title>

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="/css/remixicon/fonts/remixicon.css" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Ubuntu+Condensed&display=swap" rel="stylesheet">
    <!--link rel="stylesheet" href="/css/neutrino.css"-->

    <link rel="stylesheet" href="/dist/css/dashboard.css">
    <!-- Template CSS -->

    <style>
        .sidebar-minimized .group-label {
            display: none;
        }

        .content-header a {
            text-decoration: none !important;
        }
        .content-header a:hover {
            text-decoration: none !important;
            background: none;
        }
        .img-zoom {
            position: relative;
            transform: scale(1.3);
        }

        .zoom-img {
            transition: transform .3s ease;
        }

        .img-zoom:hover .zoom-img {
            transform: scale(1.2);
        }
    </style>
</head>

<body class="skin-dark animate">


<!-- sidebar -->
<?php echo $this->partial('partial::sidebar'); ?>
<?php //echo $this->navigation('sidebar'); ?>

<div class="content" style="background-color:#ebeeef;">
    <div class="content-header d-flex justify-content-between bg-white">
        <div class="d-flex">
            <a id="contentMenu" href="#" class="content-menu d-none d-lg-flex"><i data-feather="menu"></i></a>
            <a id="mobileMenu" href="#" class="content-menu d-lg-none"><i data-feather="menu"></i></a>

            <ul class="nav ms-5">
                <li>
                    <a href="#" class="content-menu"><i class="material-icons">refresh</i></a>
                </li>
                <li>
                    <span class="h-seperate"></span>
                </li>
                <li>
                    <a href="#" class="content-menu"><i class="material-icons">apps</i></a>
                </li>
                <li>
                    <a href="#" class="content-menu"><i class="material-icons">notifications_none</i></a>
                </li>
                <li>
                    <a href="<?=$this->url('logout');?>" class="content-menu">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            </ul>
        </div>

        <!--div>
            <a href="#" class="theme-selector link-dark" data-theme="light">
                <i data-feather="sun"></i>
            </a>
        </div-->


        <div>
            <ul class="nav quick-section">
                <li>
                    <a href="#" class="content-menu avatar online">
                        <div class="ratio ratio-1x1 overflow-hidden rounded-circle" style="width: 40px">
                        <img
                            src="<?php echo $this->avatar($user);?>"
                            alt="" class="rounded-circle img-zoom" />
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="content-menu"><i class="material-icons">tune</i></a>
                </li>
                <li>
                    <a href="#" class="content-menu"><i class="material-icons">chat</i></a>
                </li>
            </ul>
        </div>
    </div><!-- content-header -->

    <div class="content-body">
        <?php //$this->partial('partial::breadcrumb'); ?>
        <?php //$this->formatDate(new DateTime()); ?>
        <?= $this->content ?>
    </div><!-- content-body -->
</div>


<!-- Scripts -->
<!--script src="/js/feathericons/feather.min.js"></script>
<script src="/js/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="/js/jquery/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="/js/index.js"></script-->

<!--script src="/js/neutrino.js"></script-->
<script src="https://cdn.tiny.cloud/1/htnhh9y9olitjplqxt8ntddngu92tjcjajkg9i044677g1hi/tinymce/8/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>
<script src="/dist/js/dashboard.js"></script>



</body>
</html>