<section class="wrapper bg-light">
    <div class="container py-14 py-md-16">
        <div class="row">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <h2 class="fs-15 text-uppercase text-muted mb-3">What We Do?</h2>
                <h3 class="display-4 mb-9">The service we offer is specifically designed to meet your needs.</h3>
            </div>
            <!-- /column -->
        </div>
        <!-- /.row -->
        <div class="row gx-md-8 gy-8">
            <div class="col-md-6 col-lg-3">
                <div class="icon btn btn-block btn-lg btn-soft-yellow pe-none mb-5"> <i class="uil uil-phone-volume"></i> </div>
                <h4>24/7 Support</h4>
                <p class="mb-3">Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Cras justo.</p>
                <a href="#" class="more hover link-yellow">Learn More</a>
            </div>
            <!--/column -->
            <div class="col-md-6 col-lg-3">
                <div class="icon btn btn-block btn-lg btn-soft-red pe-none mb-5"> <i class="uil uil-shield-exclamation"></i> </div>
                <h4>Secure Payments</h4>
                <p class="mb-3">Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Cras justo.</p>
                <a href="#" class="more hover link-red">Learn More</a>
            </div>
            <!--/column -->
            <div class="col-md-6 col-lg-3">
                <div class="icon btn btn-block btn-lg btn-soft-leaf pe-none mb-5"> <i class="uil uil-laptop-cloud"></i> </div>
                <h4>Daily Updates</h4>
                <p class="mb-3">Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Cras justo.</p>
                <a href="#" class="more hover link-leaf">Learn More</a>
            </div>
            <!--/column -->
            <div class="col-md-6 col-lg-3">
                <div class="icon btn btn-block btn-lg btn-soft-blue pe-none mb-5"> <i class="uil uil-chart-line"></i> </div>
                <h4>Market Research</h4>
                <p class="mb-3">Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Cras justo.</p>
                <a href="#" class="more hover link-blue">Learn More</a>
            </div>
            <!--/column -->
        </div>
        <!--/.row -->
    </div>
    <!-- /.container -->
</section>
<!-- /section -->