<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @method string translate(string $message, string|null $textDomain = 'default', string|null $locale = null)
 * @method string asset(string $path)
 */
?>

<header class="wrapper bg-soft-primary">
<nav class="navbar navbar-expand-lg center-nav transparent navbar-light">
    <div class="container flex-lg-row flex-nowrap align-items-center">
        <div class="navbar-brand w-100">
            <a href="/" style="font-family: 'Ubuntu', sans-serif; font-size: 1.2rem; font-weight: 700; color: #343f52; text-decoration: none;">
                Neutrino
            </a>
        </div>
        <div class="navbar-collapse offcanvas offcanvas-nav offcanvas-start">
            <div class="offcanvas-header d-lg-none">
                <a href="/" style="font-family: 'Ubuntu', sans-serif !important; font-size: 1.65rem; font-weight: 700; color: #fff; text-decoration: none;">
                    Neutrino
                </a>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body ms-lg-auto d-flex flex-column h-100">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" href="/"><?= $this->translate('Home') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><?= $this->translate('Features') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><?= $this->translate('Pricing') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><?= $this->translate('Contacts') ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><?= $this->translate('About') ?></a>
                    </li>
                </ul>
                <!-- /.navbar-nav -->
                <div class="d-lg-none mt-auto pt-6 pb-6 order-4">
                    <a href="mailto:first.last@email.com" class="link-inverse">info@email.com</a>
                    <br /> 00 (123) 456 78 90 <br />
                    <nav class="nav social social-white mt-4">
                        <a href="#"><i class="uil uil-twitter"></i></a>
                        <a href="#"><i class="uil uil-facebook-f"></i></a>
                        <a href="#"><i class="uil uil-dribbble"></i></a>
                        <a href="#"><i class="uil uil-instagram"></i></a>
                        <a href="#"><i class="uil uil-youtube"></i></a>
                    </nav>
                    <!-- /.social -->
                </div>
                <!-- /offcanvas-nav-other -->
            </div>
            <!-- /.offcanvas-body -->
        </div>
        <!-- /.navbar-collapse -->
        <div class="navbar-other w-100 d-flex ms-auto">
            <ul class="navbar-nav flex-row align-items-center ms-auto">
                <li class="nav-item dropdown language-select text-uppercase">
                    <a class="nav-link dropdown-item dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">En</a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                            <a class="dropdown-item" href="<?= $this->url('locale.switch', ['locale' => 'en']) ?>">EN</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="<?= $this->url('locale.switch', ['locale' => 'bg']) ?>">BG</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item d-lg-none">
                    <button class="hamburger offcanvas-nav-btn"><span></span></button>
                </li>
            </ul>
            <!-- /.navbar-nav -->
        </div>
        <!-- /.navbar-other -->
    </div>
    <!-- /.container -->
</nav>
<!-- /.navbar -->
</header>