<!DOCTYPE html>
<html lang="en">
<head>
    <title>Neutrino</title>
</head>
<body>

<main>
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img
                    src="/assets/default/img/bootstrap-logo-black.svg"
                    width="40" height="32" alt="Bootstrap logo"
                    class="bi me-2 ms-2"
            >
            <span class="fs-4">Neutrino</span> </a>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">Home</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Features</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">Pricing</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">FAQs</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">About</a>
            </li>

        </ul>
    </header>

    <div>
        <?=$this->content;?>
    </div>
    
</main>

</body>
</html>

