
<h1 class="h4 mb-4">Beanstalk Queues</h1>

<div class="row">
    <div class="col-xl-4 col-md-12 col-sm-12 mb-3">
        <div class="tile tile-body bg-white p-4">
            <div class="text-dark fw-bold mb-3 d-flex justify-content-between align-items-start">
                <span>Beanstalkd</span>
                <span class="badge bg-success rounded-0">OK</span>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-transparent px-0 d-flex justify-content-between align-items-start">
                    <div>Id</div>
                    <div><?=$this->beanstalkd['id']?></div>
                </li>
                <li class="list-group-item bg-transparent px-0 d-flex justify-content-between align-items-start">
                    <div>Version</div>
                    <div><?=$this->beanstalkd['version']?></div>
                </li>
                <li class="list-group-item bg-transparent px-0 d-flex justify-content-between align-items-start">
                    <div>Uptime</div>
                    <div><?=$this->beanstalkd['uptime']?></div>
                </li>
                <li class="list-group-item bg-transparent px-0 d-flex justify-content-between align-items-start">
                    <div>Hostname</div>
                    <div><?=$this->beanstalkd['hostname']?></div>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-xl-8 col-md-12 col-sm-12 mb-3">
        <div class="tile tile-body bg-white p-4">
            <span class="text-dark fw-bold mb-3">Beanstalkd Queues</span>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Ready</th>
                    <th>Reserved</th>
                    <th>Delayed</th>
                    <th>Buries</th>
                    <th>Total</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->queues as $queue): ?>
                    <tr>
                        <td><?= htmlspecialchars($queue->name, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($queue->currentJobsReady, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($queue->currentJobsReserved, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($queue->currentJobsDelayed, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($queue->currentJobsBuried, ENT_QUOTES, 'UTF-8') ?></td>
                        <td><?= htmlspecialchars($queue->totalJobs, ENT_QUOTES, 'UTF-8') ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div>
</div>


