<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Neutrino</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Ubuntu font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap 5 -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
    >

</head>
<body>
    <main>
        <?=$this->content?>
    </main>
</body>
</html>